feat: add AdExtent to Marketing.yaml
TechForPalestine/boycott-israeli-tech-companies-dataset pull request #32
Opened 2024-01-06 14:19 UTC by pizofreude

AdExtent is one of the project involving Tal Keinan, a well-know Zionist figure in the Israeli tech and venture capital scene also former Lieutenant Colonel in Israel Air Force Reserves. He involved in many venture capital firm: Singular, Clarity Capital, KCPS Clarity that intertwined with many Hasbara and dehumanisation of Palestinians.

2024-01-07 07:12 UTC, liranelisha commented on dataset/companies/Marketing.yaml
you are missing description to the entire file and to each part

2024-01-07 09:58 UTC, pizofreude commented on dataset/companies/Marketing.yaml
Can you elaborate? I add these:
- Name: "AdExtent"
  Description: "AdExtent helps eCommerce sites turn more visitors to shoppers with personalized product marketing."
  Website: "https://adextent.com/"
  Alternatives: [https://www.thetradedesk.com/]

to dataset/companies/Marketing.yaml

Any further details I should add to the PR?

2024-01-09 15:56 UTC, abarmawi requested changes

2024-01-11 13:00 UTC, pizofreude commented on dataset/companies/Marketing.yaml
> +- Name: "AdExtent"
It should be emptied out? That's what I understood from README.

2024-01-16 12:03 UTC, abarmawi commented on dataset/companies/Marketing.yaml
@liranelisha 
```
Alternatives: 
  - Name: company name
     Website: https://www.thetradedesk.com/
    Description
```

2024-01-16 12:03 UTC, abarmawi commented on dataset/companies/Marketing.yaml
you can also run `npm run validate` to check the schema

2024-01-27 12:50 UTC, abarmawi commented on dataset/companies/Marketing.yaml
> +- Name: "AdExtent"
no it should be in this format

```
Alternatives: 
  - Name: company name
     Website: https://www.thetradedesk.com/
     Description: bla bla
```

2024-01-27 13:06 UTC, abarmawi commented
I have added the change to the marketing manually

2024-01-27 13:06 UTC, closed without merging